import type { Metadata } from "next";
import SFProDisp from "next/font/local";
import "./globals.css";
import ThemeSwitcher from "@/components/ThemeSwitcher";
import Navbar from "@/components/Navbar";

const sfProDisp = SFProDisp({
  src: [
    {
      path: '../SF-Pro-Display-Medium.otf',
      weight: '500',
      style: 'normal',
    },
    {
      path: '../SF-Pro-Display-Regular.otf',
      weight: '400',
      style: 'normal',
    },
    {
      path: '../SF-Pro-Display-Semibold.otf',
      weight: '600',
      style: 'normal',
    }
  ],
});

export const metadata: Metadata = {
  title: "Typing Test",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
      <body
        className={`${sfProDisp.className} antialiased font-normal`}
      >
        <Navbar />
        {children}
      </body>
    </html>
  );
}
