export const words: string[] = [
    "the", "and", "for", "you", "that", "with", "have", "this", "from", "they", "will", "there", "what", "about", 
    "which", "when", "can", "your", "said", "each", "how", "their", "time", "some", "these", "would", "other", "into", 
    "many", "then", "them", "write", "long", "make", "like", "more", "has", "look", "two", "way", "find", "use", "work", 
    "know", "take", "good", "new", "give", "over", "after", "just", "name", "most", "very", "think", "also", "back", 
    "where", "why", "help", "through", "before", "great", "right", "place", "small", "because", "while", "under", 
    "large", "never", "every", "might", "still", "those", "world", "again", "few", "home", "school", "family", "going", 
    "always", "until", "something", "same", "another", "around", "began", "different", "enough", "across", "during", 
    "number", "really", "should", "nothing", "better", "little", "words", "people", "water", "picture", "being", "things", 
    "father", "mother", "friend", "sister", "brother", "answer", "garden", "letter", "morning", "street", "window", 
    "yellow", "summer", "winter", "spring", "autumn", "leaves", "apple", "banana", "orange", "grape", "chair", "table", 
    "desk", "door", "happy", "funny", "strong", "quick", "smart", "fast", "slow", "today", "tomorrow", "yesterday", "soon", 
    "often", "once", "never", "ever", "maybe", "surely", "instead", "rather", "against", "between", "among", "within", 
    "without", "behind", "beside", "upon", "above", "below", "through", "toward", "along", "before", "after", "since", 
    "until", "always", "sometimes", "never", "often", "seldom", "usually", "already", "almost", "quite", "very", "just", 
    "still", "only", "both", "either", "neither", "all", "any", "some", "none", "such", "much", "many", "few", "most", 
    "several", "one", "two", "three", "first", "second", "third", "next", "last", "new", "old", "young", "early", "late", 
    "right", "wrong", "good", "bad", "best", "worst", "same", "different", "easy", "hard", "near", "far", "high", "low", 
    "deep", "tall", "short", "big", "small", "hot", "cold", "warm", "cool", "dark", "light", "heavy", "soft", "kind", 
    "true", "false", "open", "close", "begin", "end", "stop", "start", "move", "stay", "break", "fix", "push", "pull", 
    "call", "ask", "tell", "read", "write", "listen", "speak", "hear", "see", "watch", "show", "play", "jump", "run", 
    "walk", "sit", "stand", "love", "hate", "want", "need", "like", "dislike", "think", "understand", "believe", 
    "remember", "forget", "try", "learn", "teach", "follow", "lead", "happen", "change", "continue", "finish", "create", 
    "build", "destroy", "win", "lose", "fight", "share", "give", "take", "keep", "send", "bring", "leave", "return", "pay", 
    "buy", "sell", "ride", "drive", "fly", "wait", "rest", "sleep", "wake", "drink", "eat", "cook", "clean", "wear", 
    "hold", "drop", "carry", "throw", "catch", "cut", "hit", "kick", "pull", "push", "press", "touch", "feel", "hold", 
    "squeeze", "shake", "roll", "lift", "drag", "turn", "twist", "bend", "stretch", "fold", "draw", "paint", "count", 
    "measure", "mix", "pour", "fill", "empty", "pick", "choose", "guess", "hope", "dream", "smile", "laugh", "cry", 
    "sing", "dance", "shout", "whisper", "clap", "cheer", "argue", "fight", "hug", "kiss", "wave", "point", "nod", "bow", 
    "kneel", "pray", "thank", "apologize", "promise", "lie", "believe", "trust", "doubt", "fear", "worry", "wish", 
    "decide", "agree", "disagree", "forget", "know", "learn", "explain", "prove", "test", "question", "wonder", 
    "imagine", "pretend"
  ];